language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt_packages:
    - pandoc
install:
  - pip install .
script: py.test
deploy:
  - provider: releases
    api_key:
      secure: TTVYP35Oj5AS7zxwt5AgsUwmDcnhnty9XN8WztqaZqOyKmwEqbAE5WWQ03NW9oeGUMFx47RCehYhC0bl5AUAFq047dvphqD3RQU13j1cQ+069ACjJ0/b7xbvR5g8oJibJqc9C+XJX4VSuwufmeQkVAIAJYCXJ8YuqqWNokCujzXWdtwFV674RdRxx4VDsaJXOxeYIT5X/szyaTXRNpAoFcK0blKajRQR5mYVKBNXBIaEhtgPXBBhAQ0R83UmN8NbkJmPNGCTJyfbv32XNYDkODmXkcb8KNw2Nwcmgb2/byv1cxcIlg3nzx0YngwC7v5h5C4Eh9u67XxVxGMbZi1x4B2u7MNYnkN3OrzDmpOE/cd6oRlf6M1e9MzXUDwECktk7jP4CmFmWWcOHrEDFfd1bw/IzwZR8dnxO8S/UUEyxaqfckSLRBHpd6/GMes1iFALbfKSB3UDBqV/3+uFaT5zP+0Bfsnxu5hbEiXhUE1zOy0DYcUOHCoUCWtmAP/f1ZeLVkUnNNwiKffISf91zsIgFKJDc+JCgKDUuExlcp8JiMU2iIfUUuuMXvprs6durEJP9MTjaTnPozG3zN5QuYZ+8iJa7DJxZSswmoh1OnEBaN8eBq7H39PLt6xBv0nZzYMJ/Rwo2xHLL++SeBtj/0mwdm1s/t9ATeNP2nDq/kpjMjk=
    file_glob: true
    file: dist/hetio-*.tar.gz
    on:
      python: '3.6'
      repo: dhimmel/hetio
      tags: true
  - provider: pypi
    user: dhimmel
    password:
      secure: DG8uk3jcTfy6veFO7G0EpSK6KzCsCJV05dyOj/gixuZ6POJLEfOeDO97AIO1JMwZCcSfEoHQrY/udOqmh45sMShEW/CICDo4a+BkQl/7XbnNa7sul7Gz16HugkRdAG2SmqGY8ZTUnawdfn6HAnSojhduZ1xKpoxQNXwfExt/YOHKaj4c9jdknmX4m+Y6FitciA/l3Bbd98VpAvIs8rdJvSQHVKSHLXKwKLjJUF+LeWaL663sxmKJo1LcH99b805UIbf8eIpPTcY2j/sZTIavrbhSpllF864GS260yLWdSsjP/yhGtmiHrPKdlFInwoVlPMMmbrQkkocSmgLnnOe9lXekOrb7bRbE/BB3n6Q1GQWoBROLkMuQW+uP3AU9pAx9Md4b7BSkvsvRANaJrASXGxqJT5fYGjWIj4A43Giq6nhzH2wVfBpC9Qovp12mrZ0O8AS8np0FYmyJhFxc1upfA5js8UbEeHq6Kf46ka6pWaWUZG/nRr2cEXGvekbNDeXhirzNYCl+h/SLpva9iCHW3KBc+9qUKujueba63kty0j4UsS6Tfqw12r5/WNfPbQ0OxFNBBQRpFN08jmQ2kFTbFEscLgPlaxezuZ4JVOqDenWElG+no2mdiTB+o27DJHxQQnrL9XTKJgDNYSohzW19dPOtBq5bJT5L7J2ZehqMNj8=
    on:
      python: '3.6'
      repo: dhimmel/hetio
      tags: true
      distributions: sdist
      branch: deploy
